extends Control


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass

func _on_Quit_pressed():
	get_tree().quit()


func _on_Button_pressed():
	get_tree().change_scene("res://download_video.tscn")


func _on_MicTest_pressed():
	get_tree().change_scene("res://MicRecord.tscn")


func _on_DownloadPlayVid2_pressed():
	get_tree().change_scene("res://PlayVideoRecordAudio.tscn")


func _on_Settings_pressed():
	get_tree().change_scene("res://GlobalSettings.tscn")
